INFLUXDB_URL = "http://localhost:8086"
INFLUXDB_TOKEN = "L9nloLnC_Lw-8DDeG2M-5AlI2d9_aBSxDwIEMoTL4vQLlx1mtM02d7Ze28yeOh28_Xh_TOVKIkQOeJw5r4czlQ=="
INFLUXDB_ORG = "myorg"
SMART_ALARM_BUCKET = "smart_alarm_clock"
SLEEP_RATING_BUCKET = "sleep_rating"

MQTT_BROKER = "192.168.1.152f"
MQTT_PORT = 1883
MQTT_ALARM_TIME_TOPIC = "alarm/time"
MQTT_SENSOR_TOPIC = "sensors/dht22"
MQTT_ALARM_STATUS_TOPIC = "alarm/status"
